### ISSUE TITLE
Documentation structure improvement

### ISSUE THREAD

**Issue by mmajchrzak** [Knotx/knotx#197]
Although Knot.x documentation is already quite comprehensive, it's a bit difficult to go through for new Knot.x users. I'd like to propose a new structure, so the docs are more intuitive for Knot.x users and developers. I'm very happy to discuss this further.

**User guide:**
- How does Knot.x work?
  - Web page assembly
  - Running the demo
  - Basic configuration
- Fetching static templates
  - Repositories
     - Remote repositories (HTTP)
     - Local repositories (File system)
  - Templating
     - Custom Handlebars helpers
- Fetching dynamic data
  - External services (HTTP)
  - Verticles
    - Creating your own verticle
    - Deploying a verticle
  - Mock support
- Form handling
  - Forms and actions
  - Signals
  - Implementing custom action
- Custom knots
- Deployment options
- What's new

**Knot.x developers guide:**
- Internal architecture
  - Communication flow
  - Knot routing
- Knots
- Repositories
- Splitter
- Adapters
- Knot.x development
- Dependencies

**Comment by Skejven** [comment]
Documentation is re-worked in Knot.x 2 - each module has its own docs in the README files (as wiki occurs not to be the best fit for managing user/dev friendly docs).
