### ISSUE TITLE
KnotxServerRoutingTest: single test failure on local build

### ISSUE THREAD

**Issue by tMaxx** [Knotx/knotx#442]
### Version used

* knot.x: 1.3.1-SNAPSHOT

### Context of the issue/feature

Reference PR: #441

During migration of tests to newer APIs it came to light that one of the tests:

`io.knotx.server.KnotxServerRoutingTest#whenRequestingGetWithCustomFlowProcessing`

fails for no obvious reason when launched locally with either HTTP 500 (when using `WebClient`) or timeout (with `HttpClient`). At the same time Travis build passes. This should get investigated upon and fixed.

### Steps to reproduce

1. Download knotx repository
2. Remove annotation `@Disabled` for mentioned test
3. Launch this test from IDE or use `mvn test`

### Appendix

After fixing the root cause, this failed test should use `WebClient` for communication, in line with the rest of the tests.

**Comment by Skejven** [comment]
outdated
