### ISSUE TITLE
Circuit breaker mechanism for Data Bridge

### ISSUE THREAD

**Issue by tomaszmichalak** [Knotx/knotx#454]
### Context of the issue/feature

Knot.x Data Bridge allows to integrate with different data sources. When the data source is down or overloaded we should not call it but provide some fallback mechanism for the time it is not available. When the data source is back we should call the data source.

**Comment by Skejven** [comment]
This is done in Knot.x 2.0, see https://github.com/Knotx/knotx-fragments-handler/tree/master/core#circuit-breaker-action
