### ISSUE TITLE
Caching strategy for dynamic data

### ISSUE THREAD

**Issue by tomaszmichalak** [Knotx/knotx#456]
### Context of the issue/feature

Circuit breaker mechanism allows to implement a custom fallback mechanism. In many situations when the data source is not available we can provide some cached value (if it is not stale). This cache mechanism / strategy should integrate with such key-value stores like Redis itp. It should be used in Knot.x Data Bridge and Http Repository.

**Comment by Skejven** [comment]
Implemented in CB and Cache [behaviours](https://github.com/Knotx/knotx-fragments-handler/tree/master/core#behaviours).
