### ISSUE TITLE
Change default snippet tag

### ISSUE THREAD

**Issue by pun-ky** [Knotx/knotx#462]
Imagine case related with server side rendering in which I need to have both markup rendered and pure JSON beside of:

```
<script data-knotx-knots="databridge,handlebars" data-knotx-databridge-name="someSearch" type="text/knotx-snippet">
    {{#string_equals _response.statusCode "200"}}
        <script type="application/json">
            {{{_result}}}
        </script>

<ul class="items">
     {{#each _result.response.docs}}
    <li>
     <!-- .... -->
    </li>
     {{/each}}
</ul>

    {{/string_equals}}
</script>
```

and in case of HTL , nested script will be not rendered or will be not HTML compliant markup, but....
if we change knot.x snippet tag to be template tag by default, it will be correct. What is more nested template tags are valid in HTML, so that I am convinced that it just gives more flexibility without a need to configure https://github.com/Cognifide/knotx/blob/master/documentation/src/main/cheatsheet/cheatsheets.adoc#snippetoptions . 

I know that it is a breaking change, but maybe it is worth to be considered when releasing next major version.

**Comment by marcinczeczko** [comment]
But why you're putting the handlebars markup outside knotx snippet ? nothing stops you rendering it as knotx snippet

**Comment by pun-ky** [comment]
mislooking when preparing example snippet ;)

**Comment by pun-ky** [comment]
how about even non-html knot-x snippet in a form of template engine like using e.g handlebars comment syntax?

```
{{!--knotxSnippet(knots="databridge,handlebars" databridge-name="someSearch")--}}

    {{#string_equals _response.statusCode "200"}}
        <script type="application/json">
            {{{_result}}}
        </script>

<ul class="items">
     {{#each _result.response.docs}}
    <li>
     <!-- .... -->
    </li>
     {{/each}}
</ul>

    {{/string_equals}}

--}}
```

this will give ability to inject knotx into partial json, xml and so on...

**Comment by pun-ky** [comment]
what is more I am worried about nested e.g  <script type="application/json"> (SJ) tag under <script type="text/knotx-snippet"> (SK)

consider structure:

```
<SK>
    <SJ></SJ>
</SK>
```

currently: the template is broken, because knotx fragment splitter is getting as template content between `<SK></SJ>` not `<SK></SK>` because ending tag `</script>` is same for `</SK>` and `</SJ>`.

if you decide to use your separate syntax for fragments e.g upgraded syntax above:

```
{{!--#knotxSnippet:productsServerSide(knots="databridge,handlebars", databridge-name="someSearch")--}}`
...
{{!--/knotxSnippet:productsServerSide--}}`

then starting and ending tag could be unique and the problem will be solved, even so that tpl name could be used in cache and error reporting / delightful for devs.

**Comment by pun-ky** [comment]
even `<template>` could have another HTML constraints related issues so maybe better will be to have `<knotx:snippet>` as default

**Comment by tomaszmichalak** [comment]
@pun-ky Can you please check https://github.com/Knotx/knotx-stack/blob/master/knotx-it-tests/src/test/resources/content/local/fullPage.html. I think it is what you expected. It will be not configurable - we expect to have:
```
<knotx:NAMESPACE some_param=some_value>
</knotx:NAMESPACE
```
where NAMESPACE can be any value like: snippet, auth etc.

**Comment by tomaszmichalak** [comment]
Fixed, see [HTML Splitter](https://github.com/Knotx/knotx-fragments/tree/master/supplier/html-splitter).
