### ISSUE TITLE
Hard to find list of available helpers to be used within Handlebars snippets

### ISSUE THREAD

**Issue by pun-ky** [Knotx/knotx#464]
Consider adding at least link or a nice table with sample usages of all available built-in handlebars extensions. There is a documentation notes about how to extend / write own extensions but the list of currently available is missing :/ https://github.com/Cognifide/knotx/wiki/HandlebarsKnot

The answer for me was just to find that class:

https://github.com/Cognifide/knotx/blob/master/knotx-knot/knotx-knot-handlebars/src/main/java/io/knotx/knot/templating/helpers/DefaultHandlebarsHelpers.java

**Comment by marcinczeczko** [comment]
I know it's not solving the issue. But when you already started looking for available helpers, there are some that are available here: https://github.com/Knotx/knotx-handlebars-extension

**Comment by Skejven** [comment]
@pun-ky thanks for this issue. We are currently building new module [`knotx-template-engine`](https://github.com/Knotx/knotx-template-engine) that will replace existing `knot-handlebars` in the future. Section with the handlebars examples is a must have there.

**Comment by Skejven** [comment]
Done: https://github.com/Knotx/knotx-template-engine#handlebars-helpers-and-features
