### ISSUE TITLE
Cleanup duplicated code in repositories gradle builds

### ISSUE THREAD

**Issue by Skejven** [Knotx/knotx#502]
**Describe the bug**
There is a lot of duplicated code in Knot.x repositories that are part of Knot.x stack and use Gradle 5 with Kotlin to manage projects build.

**Expected behavior**
Code is packaged and distributed in one place (maybe new repo?) and re-used in projects.

**Comment by tomaszmichalak** [comment]
This is fixed with https://github.com/Knotx/knotx-gradle-plugins.
