### ISSUE TITLE
CI solution for Knot.x

### ISSUE THREAD

**Issue by tomaszmichalak** [Knotx/knotx#504]
**Is your feature request related to a problem? Please describe.**
Knot.x distribution ([Knot.x Stack](https://github.com/Knotx/knotx-stack)) consists of modules such as:
- [Knot.x HTTP Server](https://github.com/Knotx/knotx-server-http)
- [Knot.x Launcher](https://github.com/Knotx/knotx-launcher)
- [Knot.x Fragments](https://github.com/Knotx/knotx-fragments)
- etc.

Knot.x Stack artifact is a ZIP file. This file is used to build [Knot.x Docker](https://github.com/Knotx/knotx-docker) image. This image is used via [Knot.x Starter Kit](https://github.com/Knotx/knotx-starter-kit) to prepare custom, project specific Docker image - it contains its own configuration and system tests. 

All changes to any repository should validate all elements: Stack, Docker, Starter Kit.

**Describe the solution you'd like**
We want to explore Azure Pipelines to implement the CI solution for Knot.x. The initial design is a part of this task.

**Design**
1. We consider to use [Knot.x Aggregator](https://github.com/Knotx/knotx-aggregator) to clone all repositories and build Knot.x Stack using [Gradle Composite Builds](https://docs.gradle.org/current/userguide/composite_builds.html).

```
- script: |
    echo "Knot.x Stack"
    git clone https://github.com/Knotx/knotx-aggregator.git
    cd knotx-aggregator/development
    ./pull-all.sh -r modules -b $(Build.SourceBranchName)
    ./build-all.sh -r modules -d
```
Knot.x Stack artifact is stored in a local maven repository.

2. Build Knot.x Docker image

```
- script: |
    echo "Knot.x Docker"
    git clone https://github.com/Knotx/knotx-docker.git
    cd knotx-docker
    mvn clean package
```

3. Build & validate Knot.x Starter Kit

```
- script: |
    echo "Knot.x Starter Kit"
    git clone https://github.com/Knotx/knotx-starter-kit.git
    cd knotx-starter-kit
    gradle build
```

Elements to cover:
- how can we provide one pipeline definition for all repositories

**Links**
- `Build.SourceBranch`: https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml

**Comment by Skejven** [comment]
Done in https://github.com/Knotx/knotx-aggregator/pull/18
