### ISSUE TITLE
Create multiple post call sometimes

### ISSUE THREAD

**Issue by aliakbarfilmwala** [Knotx/knotx#516]
**Describe the bug**
webClient.post(dcsPort, host, path)
        .putHeader("Content-Type", "application/json;charset=utf-8")
        .rxSendJsonObject(body) sometimes make multiple calls.

**Comment by Skejven** [comment]
Hi @aliakbarfilmwala 
Please look at our [issue template](https://github.com/Knotx/knotx/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).
We need detailed information on the bug to help you.

**Comment by Skejven** [comment]
@aliakbarfilmwala I'm closing this ticket - there are not enough details. Feel free to reopen when you can provide more information.
